# Generated by Django 4.2.4 on 2023-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
