# Generated by Django 4.2.4 on 2023-08-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name_plural': 'News'},
        ),
    ]
