# Generated by Django 4.2.4 on 2023-08-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category2',
        ),
    ]
