# Generated by Django 4.2.4 on 2023-08-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0003_rename_news_news2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news2',
            options={'ordering': ['created'], 'verbose_name_plural': 'News'},
        ),
    ]
